<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NU1507;CS1591;SA1600;SYSLIB0011;CS0436;SA1629;SA1101;SA1309;SA1200;CA1822;CA2007;SA1413;SA1503;SA1500;VSTHRD200;CA1848;SA1012;SA1003;SA1005;SA1137;SA1009;SA1111;SA1201;SA1512;SA1515;CA1062;CA2227;CA1002;CA2201;CA1805;SA1402;SA1501;SA1602;SA1508;SA1124;CA1860</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

</Project>
